Website/healthy_api/app/urls.py
from django.urls import path, re_path
from app import views

urlpatterns = [

    path('', views.index, name='home'),
    path('users/', views.userList, name='user_list' ),
    path('profile/<pk>/', views.ProfileView.as_view(), name='profile')
    # re_path(r'^.*\.*', views.pages, name='pages'),

]

Website/healthy_api/healthy_api/urls.py
from django.contrib import admin
from django.urls import path, include
from api_core import views as api_core_view

from django.contrib.auth import get_user_model
from rest_framework import routers, serializers, viewsets

User = get_user_model()

class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api_core.urls')),
    path('apir/', include(router.urls)),
    path('login/', api_core_view.login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', api_core_view.register_user, name='register'),
    path('', include('app.urls')),
]

Website/healthy_api/api_core/models.py
from django import urls
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class BloodPressureData(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    bpdata = models.FloatField()
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} {self.bpdata}'


class BodyTemperatureData(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    btdata = models.FloatField()
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} {self.btdata}'


class BloodSugarData(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    bsdata = models.FloatField()
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} {self.bsdata}'

class BloodOxygenData(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    bodata = models.FloatField()
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} {self.bodata}'

class HeartBeatData(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    hbdata = models.IntegerField()
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} {self.hbdata}'


class RespirationRateData(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    rrdata = models.IntegerField()
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} {self.rrdata}'

    
class FileModel(models.Model):
    file = models.FileField(upload_to='uploaded_files/', default='')
    

Website/healthy_api/api_core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'password1')


# class LoginForm(AuthenticationForm):
#     username = forms.CharField(label='Email / Username')

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Email",                
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))

class SignUpForm(UserCreationForm):
    # username = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "placeholder" : "Username",                
    #             "class": "form-control"
    #         }
    #     ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",                
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password check",                
                "class": "form-control"
            }
        ))

    class Meta:
        model = get_user_model()
        fields = ('email', 'password1', 'password2')

Website/healthy_api/healthy_api/templates/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-icons">perm_identity</i>
            </div>
            <p class="card-category"> Number of Employees</p>
            <h3 class="card-title">100
              <small>employees</small>
            </h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons text-danger">add</i>
              <a href="#">Add new</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons">thumb_up</i>
            </div>
            <p class="card-category">Health Concious</p>
            <h3 class="card-title">25
              <small>employees</small>
            </h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">date_range</i> Last 24 Hours
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-danger card-header-icon">
            <div class="card-icon">
              <i class="material-icons">info_outline</i>
            </div>
            <p class="card-category">Health Unconcious</p>
            <h3 class="card-title">75
              <small>employees</small>
            </h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">local_offer</i> Tracked from sensor data
            </div>
          </div>
        </div>
      </div>
      
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="card card-chart">
          <div class="card-header card-header-success">
            <div class="ct-chart" id="dailySalesChart"></div>
          </div>
          <div class="card-body">
            <h4 class="card-title">Everyday Stats</h4>
            <p class="card-category">
              <span class="text-success"><i class="fa fa-long-arrow-up"></i> 25% </span> increase in today's health data.</p>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">access_time</i> updated 20 minutes ago
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card card-chart">
          <div class="card-header card-header-warning">
            <div class="ct-chart" id="websiteViewsChart"></div>
          </div>
          <div class="card-body">
            <h4 class="card-title">Health Concious vs Unconcious</h4>
            <p class="card-category">Monthwise visualization</p>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">access_time</i> 28 days ago
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card card-chart">
          <div class="card-header card-header-danger">
            <div class="ct-chart" id="completedTasksChart"></div>
          </div>
          <div class="card-body">
            <h4 class="card-title">Diabetes Data</h4>
            <!-- <p class="card-category"></p> -->
          </div>
          <!-- <div class="card-footer">
            <div class="stats">
              <i class="material-icons">access_time</i> campaign sent 2 days ago
            </div>
          </div> -->
        </div>
      </div>
    </div>
    
    <div class="col-lg-12 col-md-12">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title">Employees Stats</h4>
            <p class="card-category">Data Values of Recent Employees</p>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead class="text-warning">
                <th>ID</th>
                <th>Name</th>
                <th>Body Temperature</th>
                <th>Glucose</th>
                <th>Blood Pressure</th>
                <th>Oxygen Saturation</th>
                <th>Respiration Rate</th>
                <th>Heartbeat Rate</th>
              </thead>
              <tbody>
                {% for employee in recent_employees %}

                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{employee.first_name}} {{employee.last_name}}</td>

                    {% for bt in employee.bt %}
                    <td>{{bt.btdata}}</td>
                    {% endfor %}
                    {% for bs in employee.bs %}
                    <td>{{bs.bsdata}}</td>
                    {% endfor %}
                    {% for bp in employee.bp %}
                    <td>{{bp.bpdata}}</td>
                    {% endfor %}
                    {% for bo in employee.bo %}
                    <td>{{bo.bodata}}</td>
                    {% endfor %}
                    {% for rr in employee.rr %}
                    <td>{{rr.rrdata}}</td>
                    {% endfor %}
                    {% for hb in employee.hb %}
                    <td>{{hb.hbdata}}</td>
                    {% endfor %}
                    
                  </tr>

                {% endfor %}
                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    seriesdata = [
          [70, 72, 74, 68, 65, 68, 71],
          [30, 28, 26, 32, 35, 32, 29]
        ];
        YearlyVisualization = {
          YearlySeries :[
            [70,60,75,80,72,73,74,80,72,68,66,70],
            [30, 40, 25, 20, 28, 27, 26, 20, 28, 32, 34, 30]
          ],
        };
        diabetesData = [
          [130, 200, 180, 170, 190, 150, 120, 190]
        ];
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>

{% endblock javascripts %}

Website/healthy_api/healthy_api/templates/page-user.html
{% extends "layouts/base.html" %}

{% block title %} Page User {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

          <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Edit Profile</h4>
                  <p class="card-category">Complete your profile</p>
                </div>
                <div class="card-body">
                  <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">UserID (disabled)</label>
                          <input type="text" class="form-control" disabled value="{{ user_data.id }}">
                        </div>
                      </div>
                      <!-- <div class="col-md-3">
                        <div class="form-group">
                          <label class="bmd-label-floating">Username</label>
                          <input type="text" class="form-control" disabled value="{{ user_data.username }}">
                        </div>
                      </div> -->
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Email address</label>
                          <input type="email" class="form-control" name="email" maxlength="254" id="id_email" value="{{ user_data.email }}">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Fist Name</label>
                          <input type="text" name="first_name" class="form-control" maxlength="150" id="id_first_name" value="{{ user_data.first_name }}">
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Last Name</label>
                          <input type="text" name="first_name" class="form-control" maxlength="150" id="id_last_name" value="{{ user_data.last_name }}">
                        </div>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">Update Profile</button>
                    <div class="clearfix"></div>
                  </form>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card card-profile">
                <div class="card-avatar">
                  <a href="#">
                    <img class="img" src="/static/assets/img/faces/marc.jpg" />
                  </a>
                </div>
                <div class="card-body">
                  <h6 class="card-category text-gray">
                    {{ request.user.username }}
                  </h6>
                  <h4 class="card-title">
                    {{ request.user.email }}
                  </h4>
                  <p class="card-description">
                    Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
                  </p>
                </div>
              </div>
            </div>
          </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

Website/healthy_api/healthy_api/templates/ui-tables.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">User List</h4>
                  <p class="card-category">Details of non-admin users</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          S.No
                        </th>
                        <th>
                          Name
                        </th>
                        <th>
                          Email
                        </th>
                      </thead>
                      <tbody>
                        {% for user in users%}
                        <tr>
                          <td>
                            {{forloop.counter}}
                          </td>
                          <td>
                            {{user.first_name}} {{user.last_name}}
                          </td>
                          <td class="text-primary">
                            {{user.email}}
                          </td>
                        </tr>
                        {% endfor %}                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            
        </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}